### ISSUE TITLE
When I develop app I'd like to run tests without environment errors

### ISSUE THREAD

**Issue by DDKatch** [datarockets/rails-views#15]
Fix bugs with test environment without changes for gem core logic

<img width="579" alt="screen shot 2018-11-08 at 9 02 00 pm" src="https://user-images.githubusercontent.com/14095146/48251332-5916a280-e412-11e8-8c2c-1276284b6058.png">

**Comment by AleksSenkou** [comment]
@DDKatch can you, please, specify list of features that should be covered with tests?
