### ISSUE TITLE
Add t helper to Rails::View

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/rails-views#6]

**Comment by roman-dubrovsky** [comment]
Also add a path to locales. We can calculate locales name from class name

**Comment by DDKatch** [comment]
@roman-dubrovsky translations work [this way](http://trailblazer.to/gems/cells/rails.html#translation-and-i18n-helper) perfectly , so I think we can close this issue

**Comment by roman-dubrovsky** [comment]
But don't forget to remove the current hacks for this (if this had been added) and add some tests)

**Comment by AleksSenkou** [comment]
> But don't forget to remove the current hacks for this (if this had been added) and add some tests)

@roman-dubrovsky nothing similar was found in the codebase.
